### ISSUE TITLE
Research & preparation

### ISSUE THREAD

**Issue by kpencak** [zJavaproject/DayTripper#3]
- [ ] Find alternative for Google Places Api #4 

- [ ] Decide what kind of technology we're going to use and for what purpose (PHP mówimy nie) #5

- [ ] Set objectives to achive

- [x] Find the best solution for our project - website, app or whatever, widget maybe? #6

- [ ] Make plans for the layout #7

- [ ] Prepare enviroments #8
